### ISSUE TITLE
Module 'click' has no attribute 'INTEGER'

### ISSUE THREAD

**Issue by Perkles** [globocom/azkaban-cli#58]
I was trying to run the project and the following error occurred:

````
Traceback (most recent call last):
  File "/Workspace/vrs/my_azkaban/bin/azkaban", line 6, in <module>
    from azkaban_cli.azkaban_cli import cli
  File "/Workspace/vrs/my_azkaban/lib/python3.5/site-packages/azkaban_cli/azkaban_cli.py", line 618, in <module>
    @click.argument(u'start', type=click.INTEGER, default=0, show_default=True)
AttributeError: module 'click' has no attribute 'INTEGER'
````
Looking further I realize that the error was caused by #54 

````
@click.argument(u'start', type=click.INTEGER, default=0, show_default=True)
@click.argument(u'length', type=click.INTEGER, default=3, show_default=True)
````

`INTEGER` isn't a valid click [parameter type](https://click.palletsprojects.com/en/7.x/parameters/#parameter-types), click.INT should be used instead. Also `show_default` belongs to [`click.Option`](https://click.palletsprojects.com/en/7.x/api/#click.Option) and should not be called in [`click.Argument`](https://click.palletsprojects.com/en/7.x/api/#click.Argument)

**Comment by Perkles** [comment]
@aguimaraesduarte is this error happening just with me ?

**Comment by aguimaraesduarte** [comment]
You're right! Thanks for pointing it out, I'm pushing your fix right now.
